### ISSUE TITLE
Release compiled stuff

### ISSUE THREAD

**Issue by froboy** [AmericanMedicalAssociation/AMA-style-guide#100]
End users shouldn't need to run gulp to generate CSS files. Let's make a gulp command to generate those and then push the packaged version to the repo.

**Comment by chelsiejohnston** [comment]
@froboy can this issue be closed?

**Comment by froboy** [comment]
https://github.com/AmericanMedicalAssociation/AMA-style-guide/pull/213 should take care of this.
